// Generated by `npm run db:types`. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      actions: {
        Row: {
          feature: Database["public"]["Enums"]["feature"]
          id: string
          institution_id: string
          month: string
          rank: number
          text: string
        }
        Insert: {
          feature: Database["public"]["Enums"]["feature"]
          id?: string
          institution_id: string
          month: string
          rank: number
          text: string
        }
        Update: {
          feature?: Database["public"]["Enums"]["feature"]
          id?: string
          institution_id?: string
          month?: string
          rank?: number
          text?: string
        }
        Relationships: [
          {
            foreignKeyName: "actions_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_check_details: {
        Row: {
          audit_check_id: string
          difficulty: Database["public"]["Enums"]["difficulty"] | null
          finding: string
          how_to_fix: string | null
          source_url: string
          why_it_matters: string | null
        }
        Insert: {
          audit_check_id: string
          difficulty?: Database["public"]["Enums"]["difficulty"] | null
          finding: string
          how_to_fix?: string | null
          source_url: string
          why_it_matters?: string | null
        }
        Update: {
          audit_check_id?: string
          difficulty?: Database["public"]["Enums"]["difficulty"] | null
          finding?: string
          how_to_fix?: string | null
          source_url?: string
          why_it_matters?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_check_details_audit_check_id_fkey"
            columns: ["audit_check_id"]
            isOneToOne: true
            referencedRelation: "audit_checks"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_checks: {
        Row: {
          audit_id: string
          check_key: Database["public"]["Enums"]["check_key"]
          checked_at: string
          fix_rank: number | null
          id: string
          pillar: Database["public"]["Enums"]["pillar"]
          points_awarded: number
          points_max: number
          previous_result: Database["public"]["Enums"]["check_result"] | null
          program_id: string | null
          result: Database["public"]["Enums"]["check_result"]
          strength_rank: number | null
        }
        Insert: {
          audit_id: string
          check_key: Database["public"]["Enums"]["check_key"]
          checked_at: string
          fix_rank?: number | null
          id?: string
          pillar: Database["public"]["Enums"]["pillar"]
          points_awarded: number
          points_max: number
          previous_result?: Database["public"]["Enums"]["check_result"] | null
          program_id?: string | null
          result: Database["public"]["Enums"]["check_result"]
          strength_rank?: number | null
        }
        Update: {
          audit_id?: string
          check_key?: Database["public"]["Enums"]["check_key"]
          checked_at?: string
          fix_rank?: number | null
          id?: string
          pillar?: Database["public"]["Enums"]["pillar"]
          points_awarded?: number
          points_max?: number
          previous_result?: Database["public"]["Enums"]["check_result"] | null
          program_id?: string | null
          result?: Database["public"]["Enums"]["check_result"]
          strength_rank?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_checks_audit_id_fkey"
            columns: ["audit_id"]
            isOneToOne: false
            referencedRelation: "audits"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_checks_program_id_fkey"
            columns: ["program_id"]
            isOneToOne: false
            referencedRelation: "programs"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_program_scores: {
        Row: {
          audit_id: string
          chosen: number
          chosen_change: number | null
          discovered: number
          discovered_change: number | null
          overall: number
          overall_change: number | null
          program_id: string
          trusted: number
          trusted_change: number | null
        }
        Insert: {
          audit_id: string
          chosen: number
          chosen_change?: number | null
          discovered: number
          discovered_change?: number | null
          overall: number
          overall_change?: number | null
          program_id: string
          trusted: number
          trusted_change?: number | null
        }
        Update: {
          audit_id?: string
          chosen?: number
          chosen_change?: number | null
          discovered?: number
          discovered_change?: number | null
          overall?: number
          overall_change?: number | null
          program_id?: string
          trusted?: number
          trusted_change?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_program_scores_audit_id_fkey"
            columns: ["audit_id"]
            isOneToOne: false
            referencedRelation: "audits"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_program_scores_program_id_fkey"
            columns: ["program_id"]
            isOneToOne: false
            referencedRelation: "programs"
            referencedColumns: ["id"]
          },
        ]
      }
      audits: {
        Row: {
          chosen: number
          chosen_change: number | null
          config_version: number
          created_by: string | null
          discovered: number
          discovered_change: number | null
          id: string
          institution_id: string
          kind: Database["public"]["Enums"]["audit_kind"]
          overall: number
          overall_change: number | null
          previous_audit_id: string | null
          program_count: number
          run_at: string
          trigger: Database["public"]["Enums"]["audit_trigger"]
          trusted: number
          trusted_change: number | null
        }
        Insert: {
          chosen: number
          chosen_change?: number | null
          config_version: number
          created_by?: string | null
          discovered: number
          discovered_change?: number | null
          id?: string
          institution_id: string
          kind: Database["public"]["Enums"]["audit_kind"]
          overall: number
          overall_change?: number | null
          previous_audit_id?: string | null
          program_count?: number
          run_at?: string
          trigger: Database["public"]["Enums"]["audit_trigger"]
          trusted: number
          trusted_change?: number | null
        }
        Update: {
          chosen?: number
          chosen_change?: number | null
          config_version?: number
          created_by?: string | null
          discovered?: number
          discovered_change?: number | null
          id?: string
          institution_id?: string
          kind?: Database["public"]["Enums"]["audit_kind"]
          overall?: number
          overall_change?: number | null
          previous_audit_id?: string | null
          program_count?: number
          run_at?: string
          trigger?: Database["public"]["Enums"]["audit_trigger"]
          trusted?: number
          trusted_change?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "audits_config_version_fkey"
            columns: ["config_version"]
            isOneToOne: false
            referencedRelation: "scoring_config"
            referencedColumns: ["version"]
          },
          {
            foreignKeyName: "audits_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audits_previous_audit_id_fkey"
            columns: ["previous_audit_id"]
            isOneToOne: false
            referencedRelation: "audits"
            referencedColumns: ["id"]
          },
        ]
      }
      cities: {
        Row: {
          name: string
          state: string
        }
        Insert: {
          name: string
          state: string
        }
        Update: {
          name?: string
          state?: string
        }
        Relationships: []
      }
      demand_items: {
        Row: {
          change_pct: number | null
          count: number
          found_at: string
          id: string
          institution_id: string | null
          kind: Database["public"]["Enums"]["demand_kind"]
          language: Database["public"]["Enums"]["language"]
          meta: Json
          original_text: string | null
          pull_id: string
          rank: number | null
          sentiment: Database["public"]["Enums"]["sentiment"] | null
          source_url: string
          text: string
        }
        Insert: {
          change_pct?: number | null
          count?: number
          found_at: string
          id?: string
          institution_id?: string | null
          kind: Database["public"]["Enums"]["demand_kind"]
          language?: Database["public"]["Enums"]["language"]
          meta?: Json
          original_text?: string | null
          pull_id: string
          rank?: number | null
          sentiment?: Database["public"]["Enums"]["sentiment"] | null
          source_url: string
          text: string
        }
        Update: {
          change_pct?: number | null
          count?: number
          found_at?: string
          id?: string
          institution_id?: string | null
          kind?: Database["public"]["Enums"]["demand_kind"]
          language?: Database["public"]["Enums"]["language"]
          meta?: Json
          original_text?: string | null
          pull_id?: string
          rank?: number | null
          sentiment?: Database["public"]["Enums"]["sentiment"] | null
          source_url?: string
          text?: string
        }
        Relationships: [
          {
            foreignKeyName: "demand_items_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "demand_items_pull_id_fkey"
            columns: ["pull_id"]
            isOneToOne: false
            referencedRelation: "demand_pulls"
            referencedColumns: ["id"]
          },
        ]
      }
      demand_pulls: {
        Row: {
          id: string
          month: string
          program_key: string
          pulled_at: string
          region: string
          scope: Database["public"]["Enums"]["demand_scope"]
        }
        Insert: {
          id?: string
          month: string
          program_key: string
          pulled_at?: string
          region: string
          scope: Database["public"]["Enums"]["demand_scope"]
        }
        Update: {
          id?: string
          month?: string
          program_key?: string
          pulled_at?: string
          region?: string
          scope?: Database["public"]["Enums"]["demand_scope"]
        }
        Relationships: []
      }
      institution_status: {
        Row: {
          claimed: boolean
          claimed_at: string | null
          created_by: string | null
          institution_id: string
          is_prospect: boolean
        }
        Insert: {
          claimed?: boolean
          claimed_at?: string | null
          created_by?: string | null
          institution_id: string
          is_prospect?: boolean
        }
        Update: {
          claimed?: boolean
          claimed_at?: string | null
          created_by?: string | null
          institution_id?: string
          is_prospect?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "institution_status_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: true
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      institutions: {
        Row: {
          city: string
          created_at: string
          id: string
          instagram: string | null
          name: string
          other_links: Json
          slug: string
          state: string
          type: Database["public"]["Enums"]["institution_type"]
          website: string
          youtube: string | null
        }
        Insert: {
          city: string
          created_at?: string
          id?: string
          instagram?: string | null
          name: string
          other_links?: Json
          slug: string
          state: string
          type: Database["public"]["Enums"]["institution_type"]
          website: string
          youtube?: string | null
        }
        Update: {
          city?: string
          created_at?: string
          id?: string
          instagram?: string | null
          name?: string
          other_links?: Json
          slug?: string
          state?: string
          type?: Database["public"]["Enums"]["institution_type"]
          website?: string
          youtube?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "institutions_city_listed"
            columns: ["city", "state"]
            isOneToOne: false
            referencedRelation: "cities"
            referencedColumns: ["name", "state"]
          },
        ]
      }
      invites: {
        Row: {
          accepted_at: string | null
          accepted_by: string | null
          created_at: string
          email: string
          id: string
          institution_id: string
          invited_by: string | null
        }
        Insert: {
          accepted_at?: string | null
          accepted_by?: string | null
          created_at?: string
          email: string
          id?: string
          institution_id: string
          invited_by?: string | null
        }
        Update: {
          accepted_at?: string | null
          accepted_by?: string | null
          created_at?: string
          email?: string
          id?: string
          institution_id?: string
          invited_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "invites_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      memberships: {
        Row: {
          created_at: string
          institution_id: string
          role: Database["public"]["Enums"]["membership_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          institution_id: string
          role: Database["public"]["Enums"]["membership_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          institution_id?: string
          role?: Database["public"]["Enums"]["membership_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "memberships_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      notes: {
        Row: {
          author_id: string | null
          body: string
          created_at: string
          id: string
          institution_id: string
        }
        Insert: {
          author_id?: string | null
          body: string
          created_at?: string
          id?: string
          institution_id: string
        }
        Update: {
          author_id?: string | null
          body?: string
          created_at?: string
          id?: string
          institution_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notes_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          created_at: string
          id: string
          institution_id: string
          kind: Database["public"]["Enums"]["notification_kind"]
          link: string | null
          read: boolean
          text: string
        }
        Insert: {
          created_at?: string
          id?: string
          institution_id: string
          kind: Database["public"]["Enums"]["notification_kind"]
          link?: string | null
          read?: boolean
          text: string
        }
        Update: {
          created_at?: string
          id?: string
          institution_id?: string
          kind?: Database["public"]["Enums"]["notification_kind"]
          link?: string | null
          read?: boolean
          text?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      plans: {
        Row: {
          ends_at: string | null
          free_program_id: string | null
          institution_id: string
          set_by: string | null
          starts_at: string
          tier: Database["public"]["Enums"]["tier"]
          updated_at: string
        }
        Insert: {
          ends_at?: string | null
          free_program_id?: string | null
          institution_id: string
          set_by?: string | null
          starts_at?: string
          tier?: Database["public"]["Enums"]["tier"]
          updated_at?: string
        }
        Update: {
          ends_at?: string | null
          free_program_id?: string | null
          institution_id?: string
          set_by?: string | null
          starts_at?: string
          tier?: Database["public"]["Enums"]["tier"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "free_program_belongs"
            columns: ["free_program_id", "institution_id"]
            isOneToOne: false
            referencedRelation: "programs"
            referencedColumns: ["id", "institution_id"]
          },
          {
            foreignKeyName: "plans_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: true
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      programs: {
        Row: {
          archived_at: string | null
          created_at: string
          id: string
          institution_id: string
          name: string
          program_key: string | null
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          id?: string
          institution_id: string
          name: string
          program_key?: string | null
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          id?: string
          institution_id?: string
          name?: string
          program_key?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "programs_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          created_at: string
          id: string
          institution_id: string
          month: string
          storage_path: string
        }
        Insert: {
          created_at?: string
          id?: string
          institution_id: string
          month: string
          storage_path: string
        }
        Update: {
          created_at?: string
          id?: string
          institution_id?: string
          month?: string
          storage_path?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      rival_ads: {
        Row: {
          entered_at: string
          entered_by: string | null
          id: string
          promise: string
          rival_institution_id: string
          source_url: string
        }
        Insert: {
          entered_at?: string
          entered_by?: string | null
          id?: string
          promise: string
          rival_institution_id: string
          source_url: string
        }
        Update: {
          entered_at?: string
          entered_by?: string | null
          id?: string
          promise?: string
          rival_institution_id?: string
          source_url?: string
        }
        Relationships: [
          {
            foreignKeyName: "rival_ads_rival_institution_id_fkey"
            columns: ["rival_institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      rival_content: {
        Row: {
          id: string
          metrics: Json
          month: string
          platform: Database["public"]["Enums"]["content_platform"]
          posted_at: string | null
          rival_institution_id: string
          title: string
          url: string
          why_it_worked: string | null
        }
        Insert: {
          id?: string
          metrics?: Json
          month: string
          platform: Database["public"]["Enums"]["content_platform"]
          posted_at?: string | null
          rival_institution_id: string
          title: string
          url: string
          why_it_worked?: string | null
        }
        Update: {
          id?: string
          metrics?: Json
          month?: string
          platform?: Database["public"]["Enums"]["content_platform"]
          posted_at?: string | null
          rival_institution_id?: string
          title?: string
          url?: string
          why_it_worked?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "rival_content_rival_institution_id_fkey"
            columns: ["rival_institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      rival_moves: {
        Row: {
          description: string
          detected_at: string
          id: string
          kind: Database["public"]["Enums"]["rival_move_kind"]
          rival_institution_id: string
          source_url: string
        }
        Insert: {
          description: string
          detected_at: string
          id?: string
          kind: Database["public"]["Enums"]["rival_move_kind"]
          rival_institution_id: string
          source_url: string
        }
        Update: {
          description?: string
          detected_at?: string
          id?: string
          kind?: Database["public"]["Enums"]["rival_move_kind"]
          rival_institution_id?: string
          source_url?: string
        }
        Relationships: [
          {
            foreignKeyName: "rival_moves_rival_institution_id_fkey"
            columns: ["rival_institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      rivals: {
        Row: {
          added_at: string
          institution_id: string
          rival_institution_id: string
          suggested: boolean
        }
        Insert: {
          added_at?: string
          institution_id: string
          rival_institution_id: string
          suggested?: boolean
        }
        Update: {
          added_at?: string
          institution_id?: string
          rival_institution_id?: string
          suggested?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "rivals_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rivals_rival_institution_id_fkey"
            columns: ["rival_institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      scoring_config: {
        Row: {
          active: boolean
          created_at: string
          labels: Json
          result_shares: Json
          thresholds: Json
          version: number
          weights: Json
        }
        Insert: {
          active?: boolean
          created_at?: string
          labels: Json
          result_shares: Json
          thresholds: Json
          version: number
          weights: Json
        }
        Update: {
          active?: boolean
          created_at?: string
          labels?: Json
          result_shares?: Json
          thresholds?: Json
          version?: number
          weights?: Json
        }
        Relationships: []
      }
      share_links: {
        Row: {
          audit_id: string
          created_at: string
          created_by: string | null
          institution_id: string
          token: string
        }
        Insert: {
          audit_id: string
          created_at?: string
          created_by?: string | null
          institution_id: string
          token?: string
        }
        Update: {
          audit_id?: string
          created_at?: string
          created_by?: string | null
          institution_id?: string
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "share_links_audit_id_fkey"
            columns: ["audit_id"]
            isOneToOne: false
            referencedRelation: "audits"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "share_links_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
        ]
      }
      signals: {
        Row: {
          check_key: Database["public"]["Enums"]["check_key"]
          fetched_at: string
          id: string
          institution_id: string
          program_id: string | null
          provider: string
          source_url: string
          value: Json
        }
        Insert: {
          check_key: Database["public"]["Enums"]["check_key"]
          fetched_at: string
          id?: string
          institution_id: string
          program_id?: string | null
          provider: string
          source_url: string
          value: Json
        }
        Update: {
          check_key?: Database["public"]["Enums"]["check_key"]
          fetched_at?: string
          id?: string
          institution_id?: string
          program_id?: string | null
          provider?: string
          source_url?: string
          value?: Json
        }
        Relationships: [
          {
            foreignKeyName: "signals_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "signals_program_belongs"
            columns: ["program_id", "institution_id"]
            isOneToOne: false
            referencedRelation: "programs"
            referencedColumns: ["id", "institution_id"]
          },
        ]
      }
      team_users: {
        Row: {
          created_at: string
          role: Database["public"]["Enums"]["team_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          role: Database["public"]["Enums"]["team_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          role?: Database["public"]["Enums"]["team_role"]
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_invites: { Args: never; Returns: string }
      add_program: {
        Args: { p_name: string; p_program_key: string }
        Returns: string
      }
      archive_program: { Args: { p_program: string }; Returns: undefined }
      institution_people: {
        Args: { p_institution: string }
        Returns: {
          email: string
          joined_at: string
          role: Database["public"]["Enums"]["membership_role"]
          user_id: string
        }[]
      }
      invite_member: { Args: { p_email: string }; Returns: string }
      mark_notifications_read: { Args: { p_ids?: string[] }; Returns: number }
      onboard_institution: {
        Args: {
          p_city: string
          p_instagram: string
          p_name: string
          p_other_links: Json
          p_programs: Json
          p_state: string
          p_type: Database["public"]["Enums"]["institution_type"]
          p_website: string
          p_youtube: string
        }
        Returns: string
      }
      record_audit: { Args: { payload: Json }; Returns: string }
      remove_member: { Args: { p_user: string }; Returns: undefined }
      revoke_invite: { Args: { p_invite: string }; Returns: undefined }
      set_free_program: { Args: { p_program: string }; Returns: undefined }
      update_institution: {
        Args: {
          p_city: string
          p_instagram: string
          p_name: string
          p_other_links: Json
          p_state: string
          p_type: Database["public"]["Enums"]["institution_type"]
          p_website: string
          p_youtube: string
        }
        Returns: undefined
      }
    }
    Enums: {
      audit_kind: "free" | "paid" | "client" | "team" | "rival"
      audit_trigger: "signup" | "scheduled" | "manual"
      check_key:
        | "google_search"
        | "instagram_activity"
        | "google_profile"
        | "youtube"
        | "ai_answers"
        | "other_socials"
        | "placement_proof"
        | "review_rating"
        | "approvals"
        | "faculty_leaders"
        | "students_in_content"
        | "fees_shown"
        | "program_page"
        | "easy_enquiry"
        | "admission_steps"
        | "mobile_friendly"
        | "page_speed"
      check_result: "strong" | "okay" | "weak" | "missing"
      content_platform: "instagram" | "youtube"
      demand_kind:
        | "rising"
        | "falling"
        | "question"
        | "worry"
        | "mention"
        | "season"
        | "idea"
      demand_scope: "city" | "state" | "india"
      difficulty: "easy" | "medium" | "hard"
      feature: "audit" | "rivals" | "demand"
      institution_type: "college" | "university" | "skilling"
      language: "en" | "hi" | "as"
      membership_role: "owner" | "member"
      notification_kind:
        | "audit_ready"
        | "rival_move"
        | "demand_spike"
        | "plan_reminder"
        | "plan_ended"
      pillar: "discovered" | "trusted" | "chosen"
      rival_move_kind:
        | "new_program"
        | "fee_change"
        | "new_page"
        | "admission_dates"
      sentiment: "positive" | "negative"
      team_role: "team" | "admin"
      tier: "free" | "paid" | "client"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      audit_kind: ["free", "paid", "client", "team", "rival"],
      audit_trigger: ["signup", "scheduled", "manual"],
      check_key: [
        "google_search",
        "instagram_activity",
        "google_profile",
        "youtube",
        "ai_answers",
        "other_socials",
        "placement_proof",
        "review_rating",
        "approvals",
        "faculty_leaders",
        "students_in_content",
        "fees_shown",
        "program_page",
        "easy_enquiry",
        "admission_steps",
        "mobile_friendly",
        "page_speed",
      ],
      check_result: ["strong", "okay", "weak", "missing"],
      content_platform: ["instagram", "youtube"],
      demand_kind: [
        "rising",
        "falling",
        "question",
        "worry",
        "mention",
        "season",
        "idea",
      ],
      demand_scope: ["city", "state", "india"],
      difficulty: ["easy", "medium", "hard"],
      feature: ["audit", "rivals", "demand"],
      institution_type: ["college", "university", "skilling"],
      language: ["en", "hi", "as"],
      membership_role: ["owner", "member"],
      notification_kind: [
        "audit_ready",
        "rival_move",
        "demand_spike",
        "plan_reminder",
        "plan_ended",
      ],
      pillar: ["discovered", "trusted", "chosen"],
      rival_move_kind: [
        "new_program",
        "fee_change",
        "new_page",
        "admission_dates",
      ],
      sentiment: ["positive", "negative"],
      team_role: ["team", "admin"],
      tier: ["free", "paid", "client"],
    },
  },
} as const
