// Cities for onboarding and Demand regions: all 28 states and 8 union territories, with the
// capital and the major cities of each (a fixed list; the state is derived from the city).
// Official names are shown. Older or common names are aliases, so typing "Bangalore" still
// finds Bengaluru. Seeded into the cities table by scripts/seed.ts.

export interface City {
  name: string;
  state: string;
  aliases: readonly string[];
}

type Entry = string | readonly [name: string, ...aliases: string[]];

const STATES: Readonly<Record<string, readonly Entry[]>> = {
  'Andhra Pradesh': [
    'Amaravati',
    ['Visakhapatnam', 'Vizag', 'Vishakhapatnam'],
    ['Vijayawada', 'Bezawada'],
    'Guntur',
    'Nellore',
    'Kurnool',
    'Tirupati',
    'Kakinada',
    ['Rajamahendravaram', 'Rajahmundry'],
    ['Kadapa', 'Cuddapah'],
    ['Anantapur', 'Anantapuramu'],
    'Eluru',
    'Ongole',
    'Vizianagaram',
    'Srikakulam',
    'Chittoor',
    ['Machilipatnam', 'Masulipatnam'],
    'Tenali',
    'Proddatur',
    'Nandyal',
    'Bhimavaram',
  ],
  'Arunachal Pradesh': ['Itanagar', 'Naharlagun', 'Pasighat', 'Tawang', 'Ziro', 'Bomdila', 'Tezu', ['Aalo', 'Along'], 'Roing', 'Namsai'],
  Assam: [
    ['Guwahati', 'Gauhati', 'Dispur'],
    'Dibrugarh',
    'Jorhat',
    'Silchar',
    'Tezpur',
    'Nagaon',
    'Tinsukia',
    'Bongaigaon',
    'Dhubri',
    'Diphu',
    'North Lakhimpur',
    ['Karimganj', 'Sribhumi'],
    'Sivasagar',
    'Goalpara',
    'Barpeta',
    'Golaghat',
    'Hailakandi',
    'Mangaldoi',
    'Nalbari',
    'Kokrajhar',
    'Dhemaji',
    'Morigaon',
    'Hojai',
    'Biswanath Chariali',
    'Udalguri',
    'Lumding',
    'Haflong',
    'Duliajan',
    'Digboi',
    'Rangia',
  ],
  Bihar: [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Darbhanga',
    'Purnia',
    ['Arrah', 'Ara'],
    'Begusarai',
    'Katihar',
    'Munger',
    ['Chapra', 'Chhapra'],
    'Sasaram',
    'Hajipur',
    'Dehri',
    'Bettiah',
    'Motihari',
    'Siwan',
    'Bihar Sharif',
    'Buxar',
    'Kishanganj',
    'Sitamarhi',
    'Samastipur',
    'Madhubani',
    'Saharsa',
    'Aurangabad',
    'Nawada',
    'Jehanabad',
    'Bodh Gaya',
  ],
  Chhattisgarh: [
    'Raipur',
    ['Nava Raipur', 'Naya Raipur', 'Atal Nagar'],
    'Bhilai',
    'Durg',
    'Bilaspur',
    'Korba',
    'Rajnandgaon',
    'Jagdalpur',
    'Raigarh',
    'Ambikapur',
    'Dhamtari',
    'Mahasamund',
    'Kanker',
    'Janjgir',
    'Kawardha',
  ],
  Goa: [['Panaji', 'Panjim'], ['Margao', 'Madgaon'], 'Vasco da Gama', 'Mapusa', 'Ponda', 'Bicholim', 'Curchorem', 'Quepem'],
  Gujarat: [
    'Gandhinagar',
    ['Ahmedabad', 'Amdavad'],
    'Surat',
    ['Vadodara', 'Baroda'],
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Junagadh',
    'Anand',
    'Nadiad',
    'Mehsana',
    'Bharuch',
    'Vapi',
    'Navsari',
    'Valsad',
    'Morbi',
    'Gandhidham',
    'Bhuj',
    'Porbandar',
    'Palanpur',
    'Himmatnagar',
    'Godhra',
    'Surendranagar',
    'Amreli',
    'Veraval',
    'Patan',
    'Dahod',
    'Botad',
    'Ankleshwar',
  ],
  Haryana: [
    ['Gurugram', 'Gurgaon'],
    'Faridabad',
    'Panipat',
    'Ambala',
    'Karnal',
    'Rohtak',
    'Hisar',
    'Sonipat',
    'Yamunanagar',
    'Panchkula',
    ['Kurukshetra', 'Thanesar'],
    'Bhiwani',
    'Sirsa',
    'Jind',
    'Kaithal',
    'Rewari',
    'Palwal',
    'Bahadurgarh',
    'Jhajjar',
    'Fatehabad',
    'Narnaul',
    'Hansi',
    'Mahendragarh',
    'Nuh',
  ],
  'Himachal Pradesh': [
    'Shimla',
    ['Dharamshala', 'Dharamsala'],
    'Mandi',
    'Solan',
    'Kullu',
    'Manali',
    'Hamirpur',
    'Una',
    'Bilaspur',
    'Chamba',
    'Kangra',
    'Palampur',
    'Nahan',
    'Baddi',
    'Sundernagar',
    'Paonta Sahib',
  ],
  Jharkhand: [
    'Ranchi',
    'Jamshedpur',
    'Dhanbad',
    ['Bokaro Steel City', 'Bokaro'],
    'Deoghar',
    'Hazaribagh',
    'Giridih',
    'Ramgarh',
    ['Medininagar', 'Daltonganj'],
    'Dumka',
    'Chaibasa',
    'Chas',
    'Sahibganj',
    'Godda',
    'Lohardaga',
    'Gumla',
    'Koderma',
    'Jamtara',
    'Pakur',
  ],
  Karnataka: [
    ['Bengaluru', 'Bangalore'],
    ['Mysuru', 'Mysore'],
    ['Mangaluru', 'Mangalore'],
    ['Hubballi', 'Hubli'],
    'Dharwad',
    ['Belagavi', 'Belgaum'],
    ['Kalaburagi', 'Gulbarga'],
    ['Ballari', 'Bellary'],
    ['Vijayapura', 'Bijapur'],
    ['Shivamogga', 'Shimoga'],
    ['Tumakuru', 'Tumkur'],
    'Davanagere',
    'Udupi',
    'Manipal',
    'Hassan',
    'Mandya',
    'Chitradurga',
    'Raichur',
    'Bidar',
    ['Hosapete', 'Hospet'],
    ['Chikkamagaluru', 'Chikmagalur'],
    'Kolar',
    'Bagalkot',
    'Gadag',
    'Karwar',
    'Chikkaballapur',
    'Ramanagara',
    'Madikeri',
    'Haveri',
    'Koppal',
    'Yadgir',
    'Chamarajanagar',
    'Puttur',
  ],
  Kerala: [
    ['Thiruvananthapuram', 'Trivandrum'],
    ['Kochi', 'Cochin', 'Ernakulam'],
    ['Kozhikode', 'Calicut'],
    ['Thrissur', 'Trichur'],
    ['Kollam', 'Quilon'],
    ['Kannur', 'Cannanore'],
    ['Alappuzha', 'Alleppey'],
    ['Palakkad', 'Palghat'],
    'Kottayam',
    'Malappuram',
    'Kasaragod',
    'Pathanamthitta',
    'Thodupuzha',
    ['Kalpetta', 'Wayanad'],
    'Perinthalmanna',
    'Tirur',
    'Changanassery',
    'Aluva',
    ['Thalassery', 'Tellicherry'],
    'Muvattupuzha',
    'Kayamkulam',
    'Payyanur',
  ],
  'Madhya Pradesh': [
    'Bhopal',
    'Indore',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Dewas',
    'Satna',
    'Ratlam',
    'Rewa',
    'Katni',
    'Singrauli',
    'Burhanpur',
    'Khandwa',
    'Morena',
    'Bhind',
    'Chhindwara',
    'Guna',
    'Shivpuri',
    'Vidisha',
    'Chhatarpur',
    'Damoh',
    'Mandsaur',
    'Khargone',
    'Neemuch',
    'Pithampur',
    ['Narmadapuram', 'Hoshangabad'],
    'Itarsi',
    'Sehore',
    'Betul',
    'Seoni',
    'Datia',
    'Balaghat',
    'Tikamgarh',
    'Shahdol',
    'Mandla',
  ],
  Maharashtra: [
    ['Mumbai', 'Bombay'],
    ['Pune', 'Poona'],
    'Nagpur',
    'Thane',
    'Nashik',
    ['Chhatrapati Sambhajinagar', 'Aurangabad'],
    'Solapur',
    'Kolhapur',
    'Amravati',
    'Navi Mumbai',
    'Pimpri Chinchwad',
    'Nanded',
    'Sangli',
    'Jalgaon',
    'Akola',
    'Latur',
    'Dhule',
    ['Ahilyanagar', 'Ahmednagar'],
    'Chandrapur',
    'Parbhani',
    'Ichalkaranji',
    'Jalna',
    'Bhusawal',
    'Panvel',
    'Satara',
    'Beed',
    'Yavatmal',
    'Kalyan',
    'Vasai Virar',
    'Mira Bhayandar',
    'Bhiwandi',
    'Ulhasnagar',
    'Wardha',
    'Gondia',
    'Ratnagiri',
    'Baramati',
    'Karad',
    'Lonavala',
    ['Dharashiv', 'Osmanabad'],
    'Nandurbar',
    'Palghar',
    'Hingoli',
    'Washim',
    'Buldhana',
    'Bhandara',
    'Gadchiroli',
  ],
  Manipur: ['Imphal', 'Thoubal', 'Bishnupur', 'Churachandpur', 'Kakching', 'Ukhrul', 'Senapati', 'Moreh', 'Jiribam', 'Tamenglong'],
  Meghalaya: ['Shillong', 'Tura', 'Jowai', 'Nongpoh', 'Williamnagar', 'Baghmara', 'Nongstoin', 'Mairang', 'Resubelpara', ['Sohra', 'Cherrapunji']],
  Mizoram: ['Aizawl', 'Lunglei', 'Champhai', ['Siaha', 'Saiha'], 'Kolasib', 'Serchhip', 'Lawngtlai', 'Mamit'],
  Nagaland: ['Kohima', 'Dimapur', 'Mokokchung', 'Tuensang', 'Wokha', 'Zunheboto', 'Mon', 'Phek', ['Chumoukedima', 'Chumukedima'], 'Peren', 'Kiphire', 'Longleng'],
  Odisha: [
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    ['Berhampur', 'Brahmapur'],
    'Sambalpur',
    'Puri',
    ['Balasore', 'Baleswar'],
    'Bhadrak',
    'Baripada',
    'Jharsuguda',
    'Jeypore',
    'Angul',
    'Dhenkanal',
    'Kendrapara',
    'Jajpur',
    'Bargarh',
    'Rayagada',
    'Koraput',
    'Paradip',
    ['Balangir', 'Bolangir'],
    'Bhawanipatna',
    ['Keonjhar', 'Kendujhar'],
    'Sundargarh',
    'Phulbani',
    'Talcher',
  ],
  Punjab: [
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    ['Mohali', 'SAS Nagar', 'Sahibzada Ajit Singh Nagar'],
    'Hoshiarpur',
    'Pathankot',
    'Moga',
    ['Firozpur', 'Ferozepur'],
    'Phagwara',
    'Kapurthala',
    'Barnala',
    'Sangrur',
    'Faridkot',
    ['Sri Muktsar Sahib', 'Muktsar'],
    'Batala',
    'Rajpura',
    'Khanna',
    'Abohar',
    'Fazilka',
    'Gurdaspur',
    'Mansa',
    ['Nawanshahr', 'Shaheed Bhagat Singh Nagar'],
    ['Rupnagar', 'Ropar'],
    'Fatehgarh Sahib',
    'Tarn Taran',
    'Malerkotla',
    'Zirakpur',
  ],
  Rajasthan: [
    'Jaipur',
    'Jodhpur',
    'Udaipur',
    'Kota',
    'Ajmer',
    'Bikaner',
    'Bhilwara',
    'Alwar',
    'Sikar',
    'Bharatpur',
    'Sri Ganganagar',
    'Pali',
    'Tonk',
    'Kishangarh',
    'Beawar',
    'Hanumangarh',
    'Churu',
    'Jhunjhunu',
    'Barmer',
    'Jaisalmer',
    'Nagaur',
    'Chittorgarh',
    'Bundi',
    'Banswara',
    'Sawai Madhopur',
    'Dungarpur',
    'Dholpur',
    'Pratapgarh',
    'Jhalawar',
    'Baran',
    'Karauli',
    'Dausa',
    'Rajsamand',
    'Sirohi',
    'Mount Abu',
    'Pilani',
    'Neemrana',
    'Bhiwadi',
  ],
  Sikkim: ['Gangtok', 'Namchi', ['Gyalshing', 'Geyzing'], 'Mangan', 'Rangpo', 'Jorethang', 'Singtam', 'Pakyong', 'Soreng'],
  'Tamil Nadu': [
    ['Chennai', 'Madras'],
    'Coimbatore',
    'Madurai',
    ['Tiruchirappalli', 'Trichy'],
    'Salem',
    'Tirunelveli',
    'Tiruppur',
    'Erode',
    'Vellore',
    ['Thoothukudi', 'Tuticorin'],
    ['Thanjavur', 'Tanjore'],
    'Dindigul',
    'Hosur',
    'Nagercoil',
    'Kanchipuram',
    'Karur',
    'Kumbakonam',
    'Cuddalore',
    'Sivakasi',
    'Tiruvannamalai',
    'Pollachi',
    'Rajapalayam',
    'Namakkal',
    'Pudukkottai',
    'Karaikudi',
    'Nagapattinam',
    ['Viluppuram', 'Villupuram'],
    'Krishnagiri',
    'Dharmapuri',
    ['Ooty', 'Udhagamandalam'],
    'Kovilpatti',
    'Chengalpattu',
    'Tambaram',
    'Avadi',
    'Ramanathapuram',
    'Virudhunagar',
    'Theni',
    'Ariyalur',
    'Perambalur',
    'Tiruvallur',
    'Ranipet',
    'Tenkasi',
    'Kallakurichi',
    'Tirupattur',
    'Mayiladuthurai',
  ],
  Telangana: [
    'Hyderabad',
    'Secunderabad',
    'Warangal',
    'Karimnagar',
    'Nizamabad',
    'Khammam',
    'Ramagundam',
    ['Mahabubnagar', 'Mahbubnagar'],
    'Nalgonda',
    'Adilabad',
    'Suryapet',
    'Siddipet',
    'Miryalaguda',
    'Jagtial',
    'Mancherial',
    'Kothagudem',
    'Sangareddy',
    'Medak',
    'Vikarabad',
    'Wanaparthy',
    'Nirmal',
    'Kamareddy',
    ['Bhongir', 'Bhuvanagiri'],
    'Zaheerabad',
    'Gadwal',
  ],
  Tripura: ['Agartala', 'Udaipur', 'Dharmanagar', 'Kailashahar', 'Belonia', 'Ambassa', 'Khowai', 'Teliamura', 'Sabroom', 'Kamalpur', 'Sonamura', 'Bishalgarh'],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Ghaziabad',
    'Agra',
    ['Varanasi', 'Banaras', 'Benares', 'Kashi'],
    'Meerut',
    ['Prayagraj', 'Allahabad'],
    'Noida',
    'Greater Noida',
    'Bareilly',
    'Aligarh',
    'Moradabad',
    'Saharanpur',
    'Gorakhpur',
    'Firozabad',
    'Jhansi',
    'Muzaffarnagar',
    'Mathura',
    ['Ayodhya', 'Faizabad'],
    'Shahjahanpur',
    'Rampur',
    'Mau',
    'Hapur',
    'Etawah',
    'Mirzapur',
    'Bulandshahr',
    'Sambhal',
    'Amroha',
    'Hardoi',
    'Fatehpur',
    ['Raebareli', 'Rae Bareli'],
    'Orai',
    'Sitapur',
    'Bahraich',
    'Modinagar',
    'Unnao',
    'Jaunpur',
    'Lakhimpur',
    'Hathras',
    'Banda',
    'Pilibhit',
    'Barabanki',
    'Gonda',
    'Mainpuri',
    'Lalitpur',
    'Etah',
    'Deoria',
    'Ballia',
    'Azamgarh',
    'Sultanpur',
    'Basti',
    'Ghazipur',
    'Bijnor',
    'Pratapgarh',
    'Hamirpur',
    'Kannauj',
    'Farrukhabad',
    'Budaun',
    'Shamli',
    'Baghpat',
    'Amethi',
    'Kushinagar',
    'Bhadohi',
    ['Robertsganj', 'Sonbhadra'],
  ],
  Uttarakhand: [
    ['Dehradun', 'Dehra Dun'],
    'Haridwar',
    'Roorkee',
    'Haldwani',
    'Rudrapur',
    'Kashipur',
    'Rishikesh',
    'Nainital',
    'Almora',
    'Pithoragarh',
    'Mussoorie',
    'Kotdwar',
    'Ramnagar',
    'Srinagar',
    'Pauri',
    ['New Tehri', 'Tehri'],
    ['Gopeshwar', 'Chamoli'],
    'Bageshwar',
    'Champawat',
    'Gairsain',
    'Uttarkashi',
    'Jaspur',
    'Sitarganj',
    'Kichha',
    'Vikasnagar',
  ],
  'West Bengal': [
    ['Kolkata', 'Calcutta'],
    'Howrah',
    'Durgapur',
    'Asansol',
    'Siliguri',
    ['Bardhaman', 'Burdwan'],
    'Kharagpur',
    'Haldia',
    ['Malda', 'English Bazar'],
    ['Baharampur', 'Berhampore'],
    'Krishnanagar',
    'Barasat',
    'Barrackpore',
    'Habra',
    'Jalpaiguri',
    'Cooch Behar',
    'Balurghat',
    'Raiganj',
    'Bankura',
    'Purulia',
    ['Midnapore', 'Medinipur'],
    'Tamluk',
    ['Contai', 'Kanthi'],
    'Darjeeling',
    'Kalimpong',
    'Alipurduar',
    ['Bolpur', 'Santiniketan', 'Shantiniketan'],
    ['Chinsurah', 'Hugli', 'Hooghly'],
    'Serampore',
    'Chandannagar',
    'Kalyani',
    'Ranaghat',
    'Basirhat',
    'Diamond Harbour',
    'Suri',
    'Jangipur',
    ['Bidhannagar', 'Salt Lake'],
    ['New Town', 'Rajarhat'],
  ],
  // Union territories
  'Andaman and Nicobar Islands': [['Sri Vijaya Puram', 'Port Blair']],
  Chandigarh: ['Chandigarh'],
  'Dadra and Nagar Haveli and Daman and Diu': ['Daman', 'Silvassa', 'Diu'],
  Delhi: ['New Delhi', 'Delhi'],
  'Jammu and Kashmir': [
    'Srinagar',
    'Jammu',
    'Anantnag',
    'Baramulla',
    'Sopore',
    'Kathua',
    'Udhampur',
    'Rajouri',
    'Poonch',
    'Pulwama',
    'Kupwara',
    'Budgam',
    'Ganderbal',
    'Doda',
    'Kishtwar',
    'Samba',
    'Reasi',
    'Ramban',
    'Shopian',
    'Kulgam',
    'Bandipora',
    'Katra',
  ],
  Ladakh: ['Leh', 'Kargil'],
  Lakshadweep: ['Kavaratti', 'Agatti', 'Minicoy', 'Amini', 'Andrott'],
  Puducherry: [['Puducherry', 'Pondicherry'], 'Karaikal', 'Mahe', 'Yanam'],
};

export const UNION_TERRITORIES: readonly string[] = [
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

export const INDIA_STATES: readonly string[] = Object.keys(STATES);

export const INDIA_CITIES: readonly City[] = Object.entries(STATES).flatMap(([state, entries]) =>
  entries.map((entry) => {
    const [name, ...aliases] = typeof entry === 'string' ? [entry] : entry;
    return { name, state, aliases } satisfies City;
  }),
);

/**
 * The biggest city in each state and union territory: the nearest bigger city for the state's
 * other cities, unless NEAR_OVERRIDES names a closer one. Used for Nearby city rival
 * suggestions when a city has fewer than 3 rivals of its own (spec 8.2). Seeded as cities.near.
 */
const STATE_HUBS: Readonly<Record<string, string>> = {
  'Andhra Pradesh': 'Visakhapatnam',
  'Arunachal Pradesh': 'Itanagar',
  Assam: 'Guwahati',
  Bihar: 'Patna',
  Chhattisgarh: 'Raipur',
  Goa: 'Panaji',
  Gujarat: 'Ahmedabad',
  Haryana: 'Gurugram',
  'Himachal Pradesh': 'Shimla',
  Jharkhand: 'Ranchi',
  Karnataka: 'Bengaluru',
  Kerala: 'Kochi',
  'Madhya Pradesh': 'Indore',
  Maharashtra: 'Mumbai',
  Manipur: 'Imphal',
  Meghalaya: 'Shillong',
  Mizoram: 'Aizawl',
  Nagaland: 'Dimapur',
  Odisha: 'Bhubaneswar',
  Punjab: 'Ludhiana',
  Rajasthan: 'Jaipur',
  Sikkim: 'Gangtok',
  'Tamil Nadu': 'Chennai',
  Telangana: 'Hyderabad',
  Tripura: 'Agartala',
  'Uttar Pradesh': 'Lucknow',
  Uttarakhand: 'Dehradun',
  'West Bengal': 'Kolkata',
  'Andaman and Nicobar Islands': 'Sri Vijaya Puram',
  Chandigarh: 'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu': 'Silvassa',
  Delhi: 'Delhi',
  'Jammu and Kashmir': 'Srinagar',
  Ladakh: 'Leh',
  Lakshadweep: 'Kavaratti',
  Puducherry: 'Puducherry',
};

/** Cities whose nearest bigger city is not their state's biggest, keyed "State|City". */
const NEAR_OVERRIDES: Readonly<Record<string, string>> = {
  'Maharashtra|Pimpri Chinchwad': 'Pune',
  'Maharashtra|Amravati': 'Nagpur',
  'Maharashtra|Wardha': 'Nagpur',
  'Maharashtra|Chandrapur': 'Nagpur',
  'Karnataka|Dharwad': 'Hubballi',
  'Telangana|Secunderabad': 'Hyderabad',
  'Gujarat|Gandhinagar': 'Ahmedabad',
  'Uttar Pradesh|Greater Noida': 'Noida',
};

/** The nearest bigger city in the same state, or null for the state's biggest city. */
export function nearCity(city: { name: string; state: string }): string | null {
  const near = NEAR_OVERRIDES[`${city.state}|${city.name}`] ?? STATE_HUBS[city.state] ?? null;
  return near === city.name ? null : near;
}
