// Regenerates src/lib/supabase/database.types.ts from Drishti's local database.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fail, ROOT, runSupabase } from './lib/local.ts';

const { stdout, stderr, status } = runSupabase(['gen', 'types', 'typescript', '--local']);
if (status !== 0 || !stdout.includes('export type Database')) {
  fail(`Could not generate types. Is Drishti's local Supabase running?\n${stderr}`);
}

const target = join(ROOT, 'src', 'lib', 'supabase', 'database.types.ts');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, `// Generated by \`npm run db:types\`. Do not edit by hand.\n\n${stdout.trimEnd()}\n`, 'utf8');
console.log('Wrote src/lib/supabase/database.types.ts');
